/* Month records are separate from workspace settings and API credentials. */
(() => {
  'use strict';
  const KEY='reporter-performance-share-workspace-v1',DB='reporter-performance-share-local',TABLE='workspace',MONTH='reporter-performance-share-month/';
  let opening,lastStamp=0;
  function readLocal(){const text=localStorage.getItem(KEY);return text?JSON.parse(text):null;}
  function assemble(saved,get){if(!saved)return null;if(saved.storageFormat!==2)return saved;const months={};for(const [month,key]of Object.entries(saved.monthKeys||{})){const record=get(key);if(!record||record.month!==month||record.state?.month!==month)throw Error('月度数据读取失败：'+month);months[month]=record.state;}const active=months[saved.state.month];if(!active)throw Error('当前月份数据缺失');const archives={...months};delete archives[active.month];return {...saved,state:{...active,monthArchive:archives}};}
  function peek(){let saved;try{saved=readLocal();}catch(error){if(error instanceof SyntaxError)throw error;return null;}lastStamp=Math.max(lastStamp,saved?.savedAt||0);return assemble(saved,key=>{const text=localStorage.getItem(key);return text?JSON.parse(text):null;});}
  function open(){if(!opening)opening=new Promise((resolve,reject)=>{if(typeof indexedDB==='undefined'){reject(Error('浏览器不支持本地数据库'));return;}const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>request.result.createObjectStore(TABLE);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});return opening;}
  function getDB(db,key){return new Promise((resolve,reject)=>{const request=db.transaction(TABLE,'readonly').objectStore(TABLE).get(key);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
  async function read(){let local;try{local=readLocal();}catch(error){throw error;}let saved=local,db,useDB=false;if(typeof indexedDB!=='undefined'){try{db=await open();const other=await getDB(db,KEY);if(other&&(!saved||other.savedAt>saved.savedAt)){saved=other;useDB=true;}}catch(error){if(!saved)throw error;}}lastStamp=Math.max(lastStamp,saved?.savedAt||0);if(useDB&&saved?.storageFormat===2){const records=new Map();for(const key of Object.values(saved.monthKeys))records.set(key,await getDB(db,key));return assemble(saved,key=>records.get(key));}return assemble(saved,key=>{const text=localStorage.getItem(key);return text?JSON.parse(text):null;});}
  function write(snapshot){const frozen=JSON.parse(JSON.stringify(snapshot)),data={...frozen,savedAt:(lastStamp=Math.max(Date.now(),lastStamp+1))},entries=[];if(/^\d{4}-\d{2}$/.test(frozen.state?.month)){const months={...(frozen.state.monthArchive||{}),[frozen.state.month]:frozen.state};data.storageFormat=2;data.monthKeys={};for(const [month,source]of Object.entries(months)){const state={...source};delete state.monthArchive;const key=MONTH+month+'/'+data.savedAt;data.monthKeys[month]=key;entries.push([key,{month,state}]);}data.state={month:frozen.state.month};}let previous;try{previous=readLocal();for(const [key,value]of entries)localStorage.setItem(key,JSON.stringify(value));localStorage.setItem(KEY,JSON.stringify(data));for(const key of Object.values(previous?.monthKeys||{}))try{localStorage.removeItem?.(key);}catch{}return Promise.resolve();}catch{for(const [key]of entries)try{localStorage.removeItem?.(key);}catch{}return open().then(db=>new Promise((resolve,reject)=>{const tx=db.transaction(TABLE,'readwrite'),table=tx.objectStore(TABLE),prior=table.get(KEY);prior.onsuccess=()=>{for(const key of Object.values(prior.result?.monthKeys||{}))table.delete?.(key);};for(const [key,value]of entries)table.put(value,key);table.put(data,KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error||Error('本地自动保存失败'));tx.onabort=()=>reject(tx.error||Error('本地自动保存被中断'));}));}}
  globalThis.ProgressStore={peek,read,write};
})();
