/* Text proposals never change totals until the user confirms them. */
(function(root){
  'use strict';const E=root.PerformanceEngine;
  function options(rules,scope){return E.ruleItems(rules).filter(r=>r.id!=='p.activity.运营部'&&r.scope===scope&&r.unit==='分'&&r.score!==null&&(r.custom|| (scope==='个人'?/^(p\.content\.|p\.activity\.|p\.kind\.|p\.unpublished\.|p\.art\.base$|p\.weibo\.base$|p\.double\.points$)/:/^(d\.content\.|d\.activity\.)/).test(r.id))&&(!E.RULE_ITEMS.find(x=>x.id===r.id)||E.RULE_ITEMS.find(x=>x.id===r.id).score!==null));}
  function lines(text){return String(text).split(/\r?\n/).map(s=>s.trim()).filter(Boolean);}
  function local(text,month,scope){return lines(text).map((sourceText,sourceIndex)=>{const d=sourceText.match(/(?:(\d{4})[年\/-])?(\d{1,2})[月\/-](\d{1,2})日?/),date=d?`${d[1]||month.slice(0,4)}-${d[2].padStart(2,'0')}-${d[3].padStart(2,'0')}`:'';const platform=['国际官微','官方视频号','官方B站','团视频号','官微','团微'].find(p=>sourceText.includes(p));const level=['校级','团内','部门'].find(p=>sourceText.includes(p));const ruleId=platform?(scope==='个人'?'p.content.'+platform:'d.content.'+platform+'.'+(sourceText.includes('负责')?'负责':'参与')):level?(scope==='个人'?'p.activity.':'d.activity.')+level:'';return {sourceIndex,sourceText,date,title:sourceText.replace(d?.[0]||'','').replace(platform||'','').trim(),ruleId,role:sourceText.includes('负责')?'负责':'参与',note:ruleId?'请核对参与身份与发布状态':'描述不足，请选择适用规则',selected:!!ruleId,views:'',images:'',followers:'',hotSearch:'',link:'',activityId:'',workId:''};});}
  function proposals(data,text,month,rules,scope){
    if(!data||!Array.isArray(data.records)||data.records.length>300)throw Error('Agent 返回格式不正确');const source=lines(text),seen=new Set(),allowed=new Set(options(rules,scope).map(r=>r.id));
    const out=data.records.map(x=>{
      if(!x||!Number.isInteger(x.sourceIndex)||!source[x.sourceIndex]||seen.has(x.sourceIndex))throw Error('Agent 的来源行编号无效；请拆成每行一个项目');seen.add(x.sourceIndex);const fallback=local(source[x.sourceIndex],month,scope)[0],r={...fallback,sourceIndex:x.sourceIndex};let uncertain=!!x.uncertain;
      for(const k of ['title','ruleId','role','note','views','images','followers','hotSearch','link'])if(x[k]!==undefined)r[k]=String(x[k]??'');
      // Preserve any source date as optional metadata; accounting uses the chosen month.
      r.date=fallback.date;
      const compact=s=>s.replace(/\s/g,'');if(!compact(r.sourceText).includes(compact(r.title))||!r.title.trim()){r.title=fallback.title;uncertain=true;r.note+='；标题需核对，已保留原文';}
      if(r.role==='负责'&&!/负责|负责人/.test(r.sourceText)){r.role='参与';uncertain=true;r.note+='；负责身份无原文依据';}
      for(const key of ['views','images','followers','hotSearch'])if(r[key]!==''&&r[key]!==null&&!r.sourceText.replace(/[,，]/g,'').includes(String(r[key]))){r[key]='';uncertain=true;r.note+='；数量缺少原文依据';}
      if(r.link&&!r.sourceText.includes(r.link)){r.link='';uncertain=true;r.note+='；链接缺少原文依据';}
      if(r.ruleId.includes('.activity.')&&!/(校级|团内|部门)/.test(r.sourceText)){uncertain=true;r.note+='；活动级别需确认';}
      r.ruleId=allowed.has(r.ruleId)?r.ruleId:'';r.selected=!!r.ruleId&&!uncertain;if(!r.ruleId)r.note+='；请选择规则';return r;
    });source.forEach((s,i)=>{if(!seen.has(i))out.push({...local(s,month,scope)[0],sourceIndex:i,selected:false,note:'Agent 未识别这一行，请手动核对'});});return out.sort((a,b)=>a.sourceIndex-b.sourceIndex);
  }
  function record(row,draft,state){const rule=options(state.rules,draft.scope).find(x=>x.id===row.ruleId);if(!rule)throw Error('请选择已有的明确规则');if(!row.title.trim())throw Error('项目名称不能为空');const member=state.roster.find(m=>m.id===draft.target);if(draft.scope==='个人'&&(!member||(E.restricted(state)&&member.department!==state.department)))throw Error('请选择本部门成员');if(draft.scope==='部门'&&(!E.departmentNames(state).includes(draft.target)||(E.restricted(state)&&draft.target!==state.department)))throw Error('请选择任务所属部门');
    const identity='文字:'+E.hash(state.month+'|'+row.sourceText),r={id:'text:'+E.hash(E.stable([draft.scope,draft.target,state.month,row.sourceText,row.date,row.title,row.ruleId,row.role,row.link,row.views,row.images,row.followers,row.hotSearch,row.workId,row.activityId])),scoreScope:draft.scope,targetDepartment:draft.scope==='部门'?draft.target:'',memberId:draft.scope==='个人'?draft.target:'',title:row.title,date:row.date,accountingMonth:state.month,role:row.role||'参与',status:'已发布',workId:row.workId||identity,activityId:row.activityId||'',link:row.link,note:row.note,sourceText:row.content??row.sourceText,originalSourceText:row.sourceText,sources:[{file:'文字加分',sheet:draft.scope+'绩效加分',row:row.sourceIndex+1}],views:row.views,images:row.images,followers:row.followers,hotSearch:row.hotSearch};
    if(rule.custom){r.kind='自定义项目';r.ruleId=rule.id;r.activityId||=identity;}
    else if(rule.id.includes('.content.')){r.kind='内容';const rest=rule.id.split('.content.')[1].split('.');r.platform=rest[0];if(draft.scope==='部门'){r.role=rest[1];r.deptLead=r.role==='负责'?draft.target:'';}}
    else if(rule.id.startsWith('p.unpublished.')){r.kind='内容';r.status='未发出';r.platform=rule.id.endsWith('official')?'官微':'团微';}
    else if(rule.id.includes('.activity.')||rule.id==='p.double.points'){r.kind='现场活动';r.level=rule.id==='p.double.points'?'校级':rule.id.split('.activity.')[1];if(r.level==='运营部'){if(member?.department!=='运营部')throw Error('运营部部门活动仅适用于运营部成员');r.level='部门';}r.double=rule.id==='p.double.points';r.activityId||=identity;}
    else if(rule.id.startsWith('p.kind.')){r.kind=rule.id.slice(7);r.activityId||=identity;}
    else if(rule.id==='p.art.base'){r.kind='绘图';r.batchId=identity;if(!(+row.images>0))throw Error('绘图项目需要确认绘图张数');}
    else if(rule.id==='p.weibo.base'){r.kind='微博运营';r.activityId='微博运营:'+state.month;}
    else throw Error('此项目应由关联工作自动计算');return E.normalize(r,state.roster);
  }
  function preview(draft,state){if(draft.month!==state.month)throw Error('统计月份已变化，请重新整理');const before=E.compute(state),records=[],errors=[];for(const [i,row]of draft.rows.entries()){if(!row.selected)continue;try{records.push(record(row,draft,state));}catch(e){errors.push({index:i,message:e.message});}}const additions=[...new Map(records.filter(r=>!state.records.some(x=>x.id===r.id)).map(r=>[r.id,r])).values()];const ids=new Set(additions.map(r=>r.id));const after=E.compute({...state,records:[...state.records,...additions]});for(const i of after.pending.filter(i=>i.recordIds.some(id=>ids.has(id))))errors.push({index:-1,message:i.message});const total=c=>(draft.scope==='个人'?c.personal:c.departments).filter(l=>l.target===draft.target).reduce((s,l)=>s+l.score,0);return {additions,errors,before:total(before),after:total(after),delta:total(after)-total(before),lines:(draft.scope==='个人'?after.personal:after.departments).filter(l=>l.recordIds.some(id=>ids.has(id)))};}
  function batchEntries(tables,state){if(!tables.length)throw Error('未找到部门、姓名、工作描述三列表头');if(tables.length>300)throw Error('一次最多导入300位成员的填写行');return tables.map(source=>{const values=Object.fromEntries(Object.entries(source.values).map(([k,v])=>[k.replace(/\s/g,''),String(v??'').trim()]));const department=values.部门||'',name=values.姓名||'',text=values.工作描述||'';const matches=state.roster.filter(m=>m.active!=='离团'&&m.department===department&&m.name===name);let error='';if(!['部门','姓名','工作描述'].every(k=>Object.hasOwn(values,k)))error='表头必须为：部门、姓名、工作描述';else if(!department||!name||!text)error='部门、姓名和工作描述均不能为空';else if(E.restricted(state)&&department!==state.department)error='超出本部门任务范围';else if(matches.length!==1)error=matches.length?'同部门有同名成员，请核对名单':'名单中找不到该部门和姓名';else if(text.length>20000||lines(text).length>300)error='此行工作描述超过300个项目或20000字';return {department,name,text,source,error,status:error?'无法匹配':'待整理',draft:{scope:'个人',month:state.month,target:matches.length===1?matches[0].id:'',text,rows:[]}};});}
  function batchPreview(entries,state){let working={...state,records:[...state.records]},errors=[],additions=[];const touched=new Set();for(const [index,entry] of entries.entries()){if(entry.error||!entry.draft.rows.length)continue;const calc=preview(entry.draft,working);errors.push(...calc.errors.map(e=>({...e,entry:index,message:entry.name+'：'+e.message})));for(const r of calc.additions){if(entry.importBatchId)r.importBatchId=entry.importBatchId;r.sources.push({file:entry.source.file,sheet:entry.source.sheet,row:entry.source.row});additions.push(r);working.records.push(r);touched.add(r.memberId);}}const before=E.compute(state),after=E.compute(working),totals=after.totals.filter(t=>touched.has(t.id)).map(t=>({...t,before:before.totals.find(b=>b.id===t.id)?.score||0,delta:t.score-(before.totals.find(b=>b.id===t.id)?.score||0)}));return {additions,errors,totals};}
  root.ScoreEntry={batchEntries,batchPreview,options,lines,local,proposals,record,preview};if(typeof module!=='undefined')module.exports=root.ScoreEntry;
})(typeof globalThis!=='undefined'?globalThis:this);
