/* Scoped, lossless performance transfers. Credentials and unsaved form drafts are excluded. */
(function(root){'use strict';const E=root.PerformanceEngine;
const rulesFor=(s,scope,dep)=>s.transferRules?.[scope+'|'+dep]||s.rules;
function departments(s,scope){const out=new Set();if(scope==='个人')for(const m of s.roster)out.add(m.department);for(const r of s.records){if(scope==='个人'&&r.scoreScope!=='部门'){const m=s.roster.find(m=>m.id===r.memberId);if(m)out.add(m.department);}if(scope==='部门'&&r.scoreScope!=='个人')for(const d of r.scoreScope==='部门'?[r.targetDepartment]:[...E.split(r.deptParticipants),r.deptLead,s.roster.find(m=>m.id===r.memberId)?.department])if(d)out.add(d);}for(const a of s.adjustments)if(a.scope===scope){const d=scope==='部门'?a.target:s.roster.find(m=>m.id===a.target)?.department;if(d)out.add(d);}return E.departmentNames(s).filter(d=>out.has(d));}
function project(s,scope,department){if(!['个人','部门'].includes(scope)||!departments(s,scope).includes(department))throw Error('该月份、部门没有可导出的'+scope+'绩效数据');const out=E.clone(s),members=s.roster.filter(m=>m.department===department),ids=new Set(members.map(m=>m.id));delete out.monthArchive;delete out.importBatches;delete out.transferRuleOwners;delete out.pendingAI;delete out.pendingAICursor;delete out.transferRules;out.rules=E.clone(rulesFor(s,scope,department));out.mode='summary';out.department=department;out.roster=E.clone(members);out.records=s.records.filter(r=>scope==='个人'?r.scoreScope!=='部门'&&ids.has(r.memberId):r.scoreScope!=='个人'&&(r.scoreScope==='部门'?r.targetDepartment===department:[...E.split(r.deptParticipants),r.deptLead,s.roster.find(m=>m.id===r.memberId)?.department].includes(department))).map(r=>scope==='个人'?{...E.clone(r),scoreScope:'个人'}:{...E.clone(r),scoreScope:'部门',targetDepartment:department,memberId:'',name:''});out.adjustments=E.clone(s.adjustments.filter(a=>a.scope===scope&&(scope==='个人'?ids.has(a.target):a.target===department)));out.removedPerformanceLines=Object.fromEntries(Object.entries(s.removedPerformanceLines||{}).filter(([,v])=>v.scope===scope&&(scope==='个人'?ids.has(v.target):v.target===department)));out.batchReview=scope==='个人'?E.clone((s.batchReview||[]).filter(e=>e.department===department||ids.has(e.draft?.target))):[];
// Submission caches are scoped too, so a subsequent rebuild cannot resurrect unrelated/deleted records.
const recordIds=new Set(out.records.map(r=>r.id)),adjustmentIds=new Set(out.adjustments.map(a=>a.id));out.tasks=E.clone((s.tasks||[]).filter(t=>t.department===department));out.submissions={};for(const [id,p] of Object.entries(s.submissions||{})){if(p.department!==department)continue;out.submissions[id]={...E.clone(p),records:(p.records||[]).filter(r=>recordIds.has(id+'/'+r.id)),adjustments:(p.adjustments||[]).filter(a=>adjustmentIds.has(id+'/'+a.id))};}out.history=E.clone((s.history||[]).filter(h=>out.tasks.some(t=>t.id===h.taskId)));for(const h of out.history)if(h.previous){h.previous.records=(h.previous.records||[]).filter(r=>recordIds.has(h.taskId+'/'+r.id));h.previous.adjustments=(h.previous.adjustments||[]).filter(a=>adjustmentIds.has(h.taskId+'/'+a.id));}out.overrides=Object.fromEntries(Object.entries(out.overrides||{}).filter(([id])=>recordIds.has(id)));out.adjustmentOverrides=Object.fromEntries(Object.entries(out.adjustmentOverrides||{}).filter(([id])=>adjustmentIds.has(id)));return out;}
function payload(s,scope,department){return {schema:1,kind:'performance-data',scope,month:s.month,department,state:project(s,scope,department)};}
function validate(p,scope){if(!['个人','部门'].includes(scope)||p?.schema!==1||p.kind!=='performance-data'||p.scope!==scope||p.month!==p.state?.month||p.department!==p.state?.department)throw Error('请选择对应的'+scope+'绩效数据包');E.validateState(p.state);if(p.state.roster.some(m=>m.department!==p.department)||p.state.records.some(r=>r.scoreScope!==scope||(scope==='部门'?r.targetDepartment!==p.department:!p.state.roster.some(m=>m.id===r.memberId)))||p.state.adjustments.some(a=>a.scope!==scope||(scope==='部门'?a.target!==p.department:!p.state.roster.some(m=>m.id===a.target))))throw Error('数据包包含所选范围之外的数据');return p;}
function merge(target,p,metadata={}){validate(p,p.scope);const scope=p.scope,dep=p.department,incoming=E.clone(p.state),out=E.clone(target),batchId=metadata.batchId||E.uid(),oldRoster=E.clone(target.roster),oldIds=new Set(out.roster.filter(m=>m.department===dep).map(m=>m.id));if(scope==='个人'){for(const m of incoming.roster){const existing=out.roster.find(x=>x.id===m.id);if(existing&&existing.department!==dep)throw Error('成员内部标识与其它部门冲突，请先导出本机数据备份后处理名单');}for(const m of incoming.roster){const before=target.roster.find(x=>x.id===m.id);if(!before||before.importBatchId)m.importBatchId=batchId;else delete m.importBatchId;}const used=new Set(out.records.filter(r=>r.scoreScope==='部门').map(r=>r.memberId));out.roster=[...out.roster.filter(m=>m.department!==dep||used.has(m.id)),...incoming.roster.filter(m=>!used.has(m.id))];}const affected=r=>scope==='个人'?r.scoreScope!=='部门'&&oldIds.has(r.memberId):r.scoreScope!=='个人'&&(r.scoreScope==='部门'?r.targetDepartment===dep:[...E.split(r.deptParticipants),r.deptLead,out.roster.find(m=>m.id===r.memberId)?.department].includes(dep));
const remove=new Set(out.records.filter(affected).map(r=>r.id));for(const [task,pkg] of Object.entries(out.submissions||{})){pkg.records=(pkg.records||[]).filter(r=>!remove.has(task+"/"+r.id));for(const h of out.history||[])if(h.taskId===task&&h.previous)h.previous.records=(h.previous.records||[]).filter(r=>!remove.has(task+"/"+r.id));}out.records=out.records.flatMap(r=>{if(!remove.has(r.id))return [r];if(!r.scoreScope){const deps=[...new Set([...E.split(r.deptParticipants),r.deptLead,oldRoster.find(m=>m.id===r.memberId)?.department].filter(Boolean))];const kept=deps.filter(d=>scope==='个人'||d!==dep).map(d=>{const copy={...r,id:'preserved:'+E.hash(d)+':'+r.id,scoreScope:'部门',targetDepartment:d,memberId:'',name:''};if(copy.submissionTask){copy.originSubmissionTask=copy.submissionTask;delete copy.submissionTask;}return copy;});if(scope==='部门'){const personal={...r,scoreScope:'个人'};if(personal.submissionTask){personal.originSubmissionTask=personal.submissionTask;delete personal.submissionTask;}kept.push(personal);}return kept;}return [];});for(const r of incoming.records){r.importBatchId=batchId;if(r.submissionTask){r.originSubmissionTask=r.submissionTask;delete r.submissionTask;}if(out.records.some(x=>x.id===r.id))r.id='transfer:'+scope+':'+E.hash(dep)+':'+r.id;}out.records.push(...incoming.records);const affectedA=a=>a.scope===scope&&(scope==='个人'?oldIds.has(a.target):a.target===dep);const deletedAdjustments=new Set(out.adjustments.filter(affectedA).map(a=>a.id));for(const [task,pkg]of Object.entries(out.submissions||{})){pkg.adjustments=(pkg.adjustments||[]).filter(a=>!deletedAdjustments.has(task+'/'+a.id));for(const h of out.history||[])if(h.taskId===task&&h.previous)h.previous.adjustments=(h.previous.adjustments||[]).filter(a=>!deletedAdjustments.has(task+'/'+a.id));}out.adjustments=out.adjustments.filter(a=>!affectedA(a));for(const a of incoming.adjustments)if(out.adjustments.some(x=>x.id===a.id))throw Error('加分记录标识与其它数据冲突，未导入');for(const a of incoming.adjustments){a.importBatchId=batchId;if(a.submissionTask){a.originSubmissionTask=a.submissionTask;delete a.submissionTask;}}out.adjustments.push(...incoming.adjustments);out.removedPerformanceLines={...Object.fromEntries(Object.entries(out.removedPerformanceLines||{}).filter(([,v])=>!(v.scope===scope&&(scope==='个人'?oldIds.has(v.target):v.target===dep)))),...incoming.removedPerformanceLines};if(!target.roster.length&&!target.records.length&&!target.adjustments.length)out.rules=E.clone(incoming.rules);out.transferRules??={};out.transferRules[scope+'|'+dep]=incoming.rules;out.transferRuleOwners??={};out.transferRuleOwners[scope+'|'+dep]=batchId;
for(const r of incoming.raw){const previous=out.raw.find(x=>x.id===r.id);if(previous&&E.stable({...previous,entry:undefined,digest:undefined})!==E.stable({...r,entry:undefined,digest:undefined}))throw Error('原始文件标识冲突，未导入');if(!previous)out.raw.push(r);}out.decisions={...out.decisions,...incoming.decisions};out.audit.push(...incoming.audit);out.batchReview=scope==='个人'?[...(out.batchReview||[]).filter(e=>e.department!==dep&&!oldIds.has(e.draft?.target)),...incoming.batchReview.map(e=>({...e,id:E.uid(),importBatchId:batchId}))]:out.batchReview;registerBatch(out,target,incoming,{id:batchId,month:p.month,scope,department:dep,fileName:metadata.fileName||'绩效数据包',at:metadata.at||new Date().toISOString()});return out;}
function rows(s,scope,dep){const rules=rulesFor(s,scope,dep),calc=E.compute({...s,mode:'summary'}),columns=scope==='个人'?E.personalProjects(rules):E.ruleItems(rules).filter(r=>r.scope==='部门'&&r.unit==='分'&&r.score!==null).map(r=>({name:r.name,ruleIds:[r.id]}));columns.push({name:'其它调整',ruleIds:[]});const lines=scope==='个人'?calc.personal:calc.departments;function values(target){const v=columns.map(()=>0);for(const l of lines.filter(l=>l.target===target)){const parts=l.parts||[{ruleId:l.ruleIds[0]||'',score:l.score}];if(!l.score)continue;const total=parts.reduce((n,p)=>n+p.score,0);for(const p of parts){let i=columns.findIndex(c=>c.ruleIds.includes(p.ruleId));if(i<0)i=columns.length-1;v[i]+=total?p.score*l.score/total:l.score;} }return v.map(n=>Math.round(n*1e8)/1e8);}const headers=[scope==='个人'?'姓名':'部门',...columns.map(c=>c.name),'合计'],data=scope==='个人'?s.roster.filter(m=>m.department===dep).map(m=>[m.name,...values(m.id),calc.totals.find(x=>x.id===m.id)?.score||0]):[[dep,...values(dep),calc.deptTotals.find(x=>x.department===dep)?.score||0]];if(data.every(r=>r[r.length-2]===0)){headers.splice(-2,1);for(const r of data)r.splice(-2,1);}return [headers,...data];}

function registerBatch(s,before,incoming,batch){
  const entries=[];const memberName=id=>s.roster.find(m=>m.id===id)?.name||id;
  if(batch.scope==='个人')for(const m of incoming.roster)entries.push({id:E.uid(),kind:'member',targetId:m.id,label:m.name,content:m.position,created:m.importBatchId===batch.id});
  else entries.push({id:E.uid(),kind:'department',targetId:batch.department,label:batch.department,content:'部门绩效数据'});
  for(const r of incoming.records)entries.push({id:E.uid(),kind:'record',targetId:r.id,memberId:r.memberId,label:batch.scope==='个人'?memberName(r.memberId):batch.department,content:r.sourceText||r.title||'工作记录'});
  for(const a of incoming.adjustments)entries.push({id:E.uid(),kind:'adjustment',targetId:a.id,memberId:batch.scope==='个人'?a.target:'',label:batch.scope==='个人'?memberName(a.target):batch.department,content:a.reason||'加分记录',score:a.score});
  for(const e of s.batchReview||[])if(e.importBatchId===batch.id)entries.push({id:E.uid(),kind:'pending',targetId:e.id||'',memberId:e.draft?.target||'',label:e.name||memberName(e.draft?.target),content:e.draft?.text||e.workDescription||'待核对记录'});
  batch.entries=entries;batch.rawIds=incoming.raw.filter(r=>!before.raw.some(x=>x.id===r.id)).map(r=>r.id);s.importBatches??=[];s.importBatches.push(batch);
}
function syncBatches(s){for(const b of s.importBatches||[]){for(const r of s.records.filter(r=>r.importBatchId===b.id))if(!b.entries.some(e=>e.kind==='record'&&e.targetId===r.id))b.entries.push({id:E.uid(),kind:'record',targetId:r.id,memberId:r.memberId,label:s.roster.find(m=>m.id===r.memberId)?.name||b.department,content:r.sourceText||r.title||'工作记录'});}}
function active(s,batch,entry){if(entry.removed)return false;if(entry.kind==='record')return s.records.some(r=>r.id===entry.targetId&&r.importBatchId===batch.id);if(entry.kind==='adjustment')return s.adjustments.some(a=>a.id===entry.targetId&&a.importBatchId===batch.id);if(entry.kind==='pending')return (s.batchReview||[]).some(e=>e.importBatchId===batch.id&&(e.id||'')===entry.targetId);if(entry.kind==='department')return s.transferRuleOwners?.[batch.scope+'|'+batch.department]===batch.id;if(entry.kind==='member'){const m=s.roster.find(m=>m.id===entry.targetId);return entry.created?m?.importBatchId===batch.id:!!m&&[...s.records,...s.adjustments,...(s.batchReview||[]).map(e=>({memberId:e.draft?.target,importBatchId:e.importBatchId}))].some(r=>r.importBatchId===batch.id&&(r.memberId===m.id||r.target===m.id));}return false;}
function purge(s,recordIds,adjustmentIds){const rs=new Set(recordIds),as=new Set(adjustmentIds);s.records=s.records.filter(r=>!rs.has(r.id));s.adjustments=s.adjustments.filter(a=>!as.has(a.id));for(const id of rs)delete s.overrides?.[id];for(const id of as)delete s.adjustmentOverrides?.[id];for(const [task,pkg]of Object.entries(s.submissions||{})){const trim=p=>{p.records=(p.records||[]).filter(r=>!rs.has(task+'/'+r.id));p.adjustments=(p.adjustments||[]).filter(a=>!as.has(task+'/'+a.id));};trim(pkg);for(const h of s.history||[])if(h.taskId===task&&h.previous)trim(h.previous);}s.decisions={};}
function removeImport(s,batchId,entryId=''){syncBatches(s);
  const batch=(s.importBatches||[]).find(b=>b.id===batchId);if(!batch)throw Error('导入记录已不存在');const entry=entryId?batch.entries.find(e=>e.id===entryId):null;if(entryId&&(!entry||!active(s,batch,entry)))throw Error('这条导入数据已被移除或更新');
  const whole=!entry||entry.kind==='department',member=entry?.kind==='member'?s.roster.find(m=>m.id===entry.targetId):null,removeMember=member&&entry.created&&member.importBatchId===batch.id;
  const members=new Set(whole?s.roster.filter(m=>m.importBatchId===batch.id).map(m=>m.id):removeMember?[member.id]:[]);
  const owned=r=>r.importBatchId===batch.id;
  const recordIds=s.records.filter(r=>whole?owned(r)||members.has(r.memberId):entry.kind==='record'?r.id===entry.targetId:entry.kind==='member'?r.memberId===entry.targetId&&(removeMember||owned(r)):false).map(r=>r.id);
  const adjustmentIds=s.adjustments.filter(a=>whole?owned(a)||members.has(a.target):entry.kind==='adjustment'?a.id===entry.targetId:entry.kind==='member'?a.scope==='个人'&&a.target===entry.targetId&&(removeMember||owned(a)):false).map(a=>a.id);
  // Remove all duplicates contributing to the selected performance line, as in the performance-detail screen.
  if(entry&&['record','adjustment'].includes(entry.kind)){const calc=E.compute({...s,mode:'summary'}),lines=batch.scope==='个人'?calc.personal:calc.departments;const line=lines.find(l=>entry.kind==='record'?l.recordIds.includes(entry.targetId):l.id===(batch.scope==='个人'?'p:':'d:')+'adjust:'+entry.targetId);if(line&&!line.id.endsWith(':职务'))E.removePerformanceLine(s,batch.scope,line.target,line.id);}
  purge(s,recordIds,adjustmentIds);s.roster=s.roster.filter(m=>!members.has(m.id));s.batchReview=(s.batchReview||[]).filter(e=>!(whole&&e.importBatchId===batch.id)&&!members.has(e.draft?.target)&&!(entry?.kind==='member'&&e.importBatchId===batch.id&&e.draft?.target===entry.targetId)&&!(entry?.kind==='pending'&&e.importBatchId===batch.id&&(e.id||'')===entry.targetId));
  for(const [id,x]of Object.entries(s.removedPerformanceLines||{}))if(members.has(x.target)||(whole&&x.scope===batch.scope&&x.target===batch.department))delete s.removedPerformanceLines[id];
  const key=batch.scope+'|'+batch.department;if(whole&&s.transferRuleOwners?.[key]===batch.id){delete s.transferRules?.[key];delete s.transferRuleOwners[key];}
  if(entry)entry.removed=true;else for(const e of batch.entries)e.removed=true;
  if(!batch.entries.some(e=>active(s,batch,e))){batch.removedAt=new Date().toISOString();const referenced=new Set([...s.records,...s.adjustments].flatMap(r=>(r.sources||[]).map(x=>x.fileId||x.rawId).filter(Boolean)));s.raw=s.raw.filter(r=>!batch.rawIds.includes(r.id)||referenced.has(r.id)||(s.importBatches||[]).some(b=>b.id!==batch.id&&b.entries.some(e=>active(s,b,e))));}
  if(!entry)s.importBatches=(s.importBatches||[]).filter(b=>b.id!==batch.id);else batch.entries=batch.entries.filter(e=>active(s,batch,e));return batch;
}
function combinedDepartmentRows(s,deps){const tables=deps.map(d=>rows(s,'部门',d)),headers=['部门'];for(const t of tables)for(const h of t[0].slice(1,-1))if(!headers.includes(h))headers.push(h);headers.push('合计');return [headers,...tables.flatMap(t=>t.slice(1).map(row=>{const values=Object.fromEntries(t[0].map((h,i)=>[h,row[i]]));return headers.map(h=>values[h]??0);} ))];}
const api={departments,project,payload,validate,merge,rows,rulesFor,active,syncBatches,removeImport,combinedDepartmentRows};root.PerformanceTransfer=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
